version: "3"
services:
  mysql-server:
    container_name: mysql
    image: mysql
    restart: always
    ports:
      # 左边宿主机的端口可以修改成别的,比如: 3309:3306
      - 3308:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
