version: "3"
services:
  redis-server:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --requirepass 123456
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  redis-data:
    